apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-worker
  namespace: ecommerce-service
  labels:
    app: catalog-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-worker
  template:
    metadata:
      labels:
        app: catalog-worker
    spec:
      containers:
      - name: catalog-worker
        image: our-dockerhub-username/order-worker:latest # Replace with your actual registry path
        envFrom:
        - configMapRef:
            name: ecommerce-config
        - secretRef:
            name: ecommerce-secrets
            