apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  QueueSettings__Host: "rabbitmq"
  QueueSettings__Username: "myuser"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-service
type: Opaque
data:
  ConnectionStrings__Order: SG9zdD1PcmRlckRiO1BvcnQ9NTQzMjtEYXRhYmFzZT1vcmRlcjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlcw==
  ConnectionStrings__Catalog: SG9zdD1DYXRhbG9nRGI7UG9ydD01NDMyO0RhdGFiYXNlPWNhdGFsb2c7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM=
  QueueSettings__Password: bXlwYXNzd29yZA==
  Db__Password: cG9zdGdyZXM=