apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-worker
  namespace: ecommerce-service
  labels:
    app: order-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      containers:
      - name: order-worker
        image: your-dockerhub-username/order-worker:latest # Replace with your actual registry path
        envFrom:
        - configMapRef:
            name: ecommerce-config
        - secretRef:
            name: ecommerce-secrets
